### ISSUE TITLE
The results are bad? 

### ISSUE THREAD

**Issue by zsl2018** [msxie92/ScreenStyle#1]
Why the results are so bad using your pretrained models and your test data? May be I made a mistake using your code? Can you reply m
<img width="361" alt="Screen Shot 2021-11-20 at 2 40 27 PM" src="https://user-images.githubusercontent.com/36988055/142717243-12fdfad7-c228-4f6b-aa0a-87473e02b7ef.png">
<img width="420" alt="Screen Shot 2021-11-20 at 2 40 58 PM" src="https://user-images.githubusercontent.com/36988055/142717274-89f84bd6-a8c1-4482-98c2-cba116fc2ef6.png">
e？

**Comment by msxie92** [comment]
I just found that the weight of the ScreenVAE model was wrong. I have uploaded the correct one.
Sorry for the inconvenience caused.
